const GET_REPOS = 'REPOS/GET_REPOS'
const GET_ISSUES = 'REPOS/GET_ISSUES'
const CLOSE_ISSUES = 'ISSUES/CLOSE_ISSUES'
const GET_CARS = 'MAPTAB/GET_CARS'
const SELECT_CAR = 'MAPTAB/SELECT_CAR'
const UNSELECT_CAR = 'MAPTAB/UNSELECT_CAR'
const REPOS_TAB = 'APP/REPOS_TAB'
const MAP_TAB = 'APP/MAP_TAB'
const REPOS_SHOW_LOADER = 'REPOS/SHOW_LOADER'
const REPOS_HIDE_LOADER = 'REPOS/HIDE_LOADER'
const ISSUES_SHOW_LOADER = 'ISSUES/SHOW_LOADER'
const ISSUES_HIDE_LOADER = 'ISSUES/HIDE_LOADER'

export {GET_REPOS,GET_ISSUES,CLOSE_ISSUES,GET_CARS,SELECT_CAR,UNSELECT_CAR,REPOS_TAB,MAP_TAB,REPOS_SHOW_LOADER,REPOS_HIDE_LOADER,ISSUES_SHOW_LOADER,ISSUES_HIDE_LOADER}
