const GET_REPOS = 'REPOS/GET_REPOS'
const GET_ISSUES = 'REPOS/GET_ISSUES'
const CLOSE_ISSUES = 'ISSUES/CLOSE_ISSUES'
const GET_CARS = 'MAPTAB/GET_CARS'
const SELECT_CAR = 'MAPTAB/SELECT_CAR'
const UNSELECT_CAR = 'MAPTAB/UNSELECT_CAR'
export {GET_REPOS,GET_ISSUES,CLOSE_ISSUES,GET_CARS,SELECT_CAR,UNSELECT_CAR}
